### ISSUE TITLE
 Can't resolve 'react-json-tree' in \node_modules\@bb-tech\ra-components\dist

### ISSUE THREAD

**Issue by pacau999** [BigBasket/ra-components#17]
Can't resolve 'react-json-tree' in \node_modules\@bb-tech\ra-components\dist
 Instaleld via yarn

**Comment by sivaavkd** [comment]
react-json-tree is a peer dependency.  Please add it to the package.json of your project.
 https://www.npmjs.com/package/react-json-tree
